-- Imported once from data/csv/supplier-seed-data.csv. Later restarts preserve admin edits.
INSERT INTO locations(id,name) VALUES
('blk-as8','Blk AS8'),
('com2','COM2'),
('com3','COM3'),
('central-library','Central Library'),
('engineering-block-e3','Engineering Block E3'),
('engineering-block-e4','Engineering Block E4'),
('engineering-block-ea','Engineering Block EA'),
('frontier','Frontier'),
('hon-sui-sen-memorial-library','Hon Sui Sen Memorial Library'),
('medicine-science-library','Medicine+Science Library'),
('prince-george-s-park','Prince George''s Park'),
('terrace','Terrace'),
('the-ridge','The Ridge'),
('yusof-ishak-house','Yusof Ishak House'),
('innovation4-0','innovation4.0');

INSERT INTO suppliers(name,category,location_id,description) VALUES
('Anna''s x Soup Union','food','central-library','Floor 1; Next to NUS Co-op'),
('NUS Co-op','retail','central-library','Floor 1; Inside the library on the right side'),
('Printer @ Com 2','printing','com2','Floor 1; Next to LT19'),
('Cool Spot','food','com2','Floor 1; Opp LT16'),
('InstaChef','food','terrace','Floor 1; Next to foyer'),
('Cafe+ Robot Cafe','food','central-library','Floor 1; Opp to central library entrance'),
('A Hot Hideout','food','prince-george-s-park','Floor 2; Near PGP entrance'),
('Arise and Shine','food','engineering-block-e4','Floor 4; Near LT6'),
('Bakehaus / Aurea','food','the-ridge','Floor 1; Near COM2'),
('Central Square @ YIH','food','yusof-ishak-house','Floor 1; Closest to Opp UHC bus stop'),
('Pasta Express','food','frontier','Floor 1; Aircon section'),
('TOMORO COFFEE','food','hon-sui-sen-memorial-library','Floor 2; Inside HSSML'),
('Octobox','retail','prince-george-s-park','Floor 2; Near PGP entrance'),
('Smooy','food','com3','Floor 1; The Terrace @ COM3'),
('Goh Bros E-Print Pte Ltd','printing','yusof-ishak-house','Floor 5; Take the long staircase up YIH'),
('Cheers Unmanned Convenience Store','retail','engineering-block-e3','Floor 4; Take right from Arise n Shine'),
('Nami','food','innovation4-0','Floor 1; Opp TCOMS'),
('Supersnacks','food','prince-george-s-park','Floor 1; At level 1 in Prince George''s Park Residences, Block 10'),
('Good Day Cafe','food','medicine-science-library','Floor 1; Inside MedScience library'),
('The Coffee Roaster','food','blk-as8','Floor 1; Behind central library bus stop'),
('he by He Brews','food','engineering-block-ea','Floor 1; Near LT7 & Engineering Auditorium');
